spring.application.name=neobank
spring.datasource.url=jdbc:postgresql://localhost:5432/neobank
spring.datasource.username=postgres
spring.datasource.password=q654321q
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true